^e::
m := ComObjCreate("Outlook.Application").CreateItem(0)
m.Subject := "test mail"
m.To := "vimal.s2@hpe.com"
m.Body :="hi vimal `n`n this mail generated by machine do not reply `n`n`n`n` thanks and regards`n dhayanithi.s"
m.Display ;
m.Send ;  